### ISSUE TITLE
remove old win-32 versions

### ISSUE THREAD

**Issue by scottdraves** [conda-forge/beakerx-feedstock#9]
i published some win32 versions of my package (beakerx) by mistake.
these packages would never work.
now we are stuck with an old version that appears confusing:
https://anaconda.org/conda-forge/beakerx

is there any way to delete these (all old win-32 versions).

**Comment by jakirkham** [comment]
Looks like @isuruf removed them all. Can you please confirm that this is correct @scottdraves?

**Comment by scottdraves** [comment]
they were marked as broken, which fixes the problem of someone trying to install them, but is still a bit confusing since win32 still shows up as installable where people are most likely to look:
![screen shot 2017-11-16 at 4 34 21 pm](https://user-images.githubusercontent.com/963093/32917086-097bb214-caec-11e7-8fe9-7ee5a41777d5.png)

**Comment by jakirkham** [comment]
Well marking them as `broken` is our policy as we do not like to delete packages. There is a long history behind this and am happy to point out relevant threads if they are of interest.

I suppose an issue could be raised with [Anaconda-Platform]( https://github.com/Anaconda-Platform/support/issues ) about how this is represented. Otherwise I don't think there is much more we can do here.

**Comment by scottdraves** [comment]
thanks!  i did that.
